### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by vitobotta** [fleck/nitrous-oxide#1]
Hi! I am trying this - I took a note when you suggested it in https://github.com/hotwired/turbo/issues/105#issuecomment-778788833.

```javascript
import { goFast } from "../lib/nitrous-oxide";
goFast();
```

That path won't work I think since I am using the library as installed with yarn. I'm not too good with js so can you kindly tell me what the import line should be exactly?

I tried with 

```javascript
import { goFast } from "nitrous-oxide";
```

but I get `Uncaught ReferenceError: exports is not defined` for

```
Object.defineProperty(exports, "__esModule", {
```

Thanks!

**Comment by fleck** [comment]
Good catch on the relative path in the readme! just added a commit to update the readme. As for the error you're getting, do you have some more details about your setup? Also, does importing any other libs work for you?

**Comment by vitobotta** [comment]
Hi, for now I just updated my gist (https://gist.github.com/vitobotta/8ac3c6f65633b5edb2949aeff0dec69b) to make it work with the latest Turbo, since I had some other customizations and don't have the time now to investigate more. I will try nitrous-oxide again as soon as I have the time. Thanks! :)

**Comment by fleck** [comment]
Thanks for trying out the package. If you run into any other issues let me know and I may be able out!
